name: Trigger auto deployment for container-app-nfr6zfoazlo54

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container-app-nfr6zfoazlo54-AutoDeployTrigger-52268c63-0660-42c7-81d5-45bd8657764f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNFR6ZFOAZLO54_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNFR6ZFOAZLO54_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNFR6ZFOAZLO54_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrynfr6zfoazlo54.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPNFR6ZFOAZLO54_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNFR6ZFOAZLO54_REGISTRY_PASSWORD }}
          containerAppName: container-app-nfr6zfoazlo54
          resourceGroup: learnclouddemo2a8f7
          imageToBuild: containerregistrynfr6zfoazlo54.azurecr.io/container-app-nfr6zfoazlo54:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


